### ISSUE TITLE
Error: Cannot find module 'please-upgrade-node'

### ISSUE THREAD

**Issue by hugovk** [pre-commit/pre-commit.com#406]
With this PR: https://github.com/hugovk/tinytext/pull/59
With this config: https://github.com/hugovk/tinytext/blob/master/.pre-commit-config.yaml

The Prettier hook failed:

```
pyupgrade................................................................Passed
black....................................................................Passed
isort....................................................................Passed
flake8...................................................................Passed
check blanket noqa.......................................................Passed
Check for merge conflicts................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
mypy.....................................................................Passed
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'please-upgrade-node'
Require stack:
- /pc/clone/89rCdSwwReu-UQrdqlPxWw/src/cli/index.js
- /pc/clone/89rCdSwwReu-UQrdqlPxWw/bin/prettier.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/pc/clone/89rCdSwwReu-UQrdqlPxWw/src/cli/index.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/pc/clone/89rCdSwwReu-UQrdqlPxWw/src/cli/index.js',
    '/pc/clone/89rCdSwwReu-UQrdqlPxWw/bin/prettier.js'
  ]
}
```

https://results.pre-commit.ci/run/github/89922502/1603910359.7titBuVPQISl6WxqA7LTkA

**Comment by asottile** [comment]
you're looking for https://github.com/pre-commit-ci/issues/issue/2
